export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'
export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL'


export const GET_CONTACT_REQUEST = 'GET_CONTACT_REQUEST'
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS'
export const GET_CONTACT_FAIL = 'GET_CONTACT_FAIL'

export const GET_CONTACT_BYID_REQUEST = 'GET_CONTACT_BYID_REQUEST'
export const GET_CONTACT_BYID_SUCCESS = 'GET_CONTACT_BYID_SUCCESS'
export const GET_CONTACT_BYID_FAIL = 'GET_CONTACT_BYID_FAIL'

export const EDIT_CONTACT_REQUEST = 'EDIT_CONTACT_REQUEST'
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS'
export const EDIT_CONTACT_FAIL = 'EDIT_CONTACT_FAIL'


export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL'
